#!/usr/bin/env python
#============================================================================
# Copyright (C) Microsoft Corporation, All rights reserved. 
#============================================================================

import os
import imp
import re
import codecs
import shutil
import string

protocol = imp.load_source('protocol', '../protocol.py')
nxDSCLog = imp.load_source('nxDSCLog', '../nxDSCLog.py')

LG = nxDSCLog.DSCLog

inventoryMof_path = '/etc/opt/microsoft/omsagent/conf/omsagent.d/'

def init_vars(Instances):
    new_instances = []
    if Instances is not None :
        for instance in Instances:
            if instance['InstanceName'].value is not None:
                instance['InstanceName']=instance['InstanceName'].value

            if instance['ClassName'].value is not None:
                instance['ClassName']=instance['ClassName'].value

            new_properties = []
            if instance['Properties'] is not None and len(instance['Properties'].value) > 0:
                for property in instance['Properties'].value:
                    if property is not None and len(property) > 0:
                        new_properties.append(property)

            if len(new_properties) > 0:
                instance['Properties'] = new_properties
                new_instances.append(instance)

    Instances = new_instances
    
def Set_Marshall(FileName, Enable = False, Instances = None, RunIntervalInSeconds = 300, Tag = "default", Format = "tsv", FilterType = "filter_changetracking", Configuration = None):
    init_vars(Instances)
    Set(FileName, Enable, Instances, RunIntervalInSeconds, Tag, Format, FilterType, Configuration)
    return [0]

def Test_Marshall(FileName, Enable = False, Instances = None, RunIntervalInSeconds = 300, Tag = "default", Format = "tsv", FilterType = "filter_changetracking", Configuration = None):
    init_vars(Instances)
    return Test(Enable, Instances)

def Get_Marshall(FileName, Enable = False, Instances = None, RunIntervalInSeconds = 300, Tag = "default", Format = "tsv", FilterType = "filter_changetracking", Configuration = None):
    arg_names = list(locals().keys())
    init_vars(Instances)
    
    CurrentInstances = Instances
    FileName = protocol.MI_String(FileName)
    Enable = protocol.MI_Boolean(Enable)
    for instance in CurrentInstances:
        instance['InstanceName'] = protocol.MI_String(instance['InstanceName'])
        instance['ClassName'] = protocol.MI_String(instance['ClassName'])
        if instance['Properties'] is not None and len(instance['Properties']):
            instance['Properties'] = protocol.MI_StringA(instance['Properties'])
    Instances = protocol.MI_InstanceA(CurrentInstances)
    retd = {}
    ld = locals()
    for k in arg_names:
        retd[k] = ld[k]
    return 0, retd
            
def Set(FileName, Enable, Instances, RunIntervalInSeconds, Tag, Format, FilterType, Configuration):
    if Enable == True:
         GenerateInventoyMOF(FileName, Instances, RunIntervalInSeconds, Tag, Format, FilterType, Configuration)
    return [0]

def Test(Enable, Instances):
    return [-1]

def GenerateInventoyMOF(FileName, Instances, RunIntervalInSeconds, Tag, Format, FilterType, Configuration):
    header = 'This is an autogenerated file \n/*@TargetNode=\'Localhost\'*/\n'
    footer= '\ninstance of OMI_ConfigurationDocument \n{\n \
    DocumentType = \"inventory\"; \n \
    Version=\"2.0.0\"; \n \
    MinimumCompatibleVersion = \"2.0.0\"; \n \
    Name=\"InventoryConfig\"; \n};'

    inventoryMofSection = ''
    if Instances is not None:
        for instance in Instances:
            instanceName = instance['InstanceName']
            className = instance['ClassName']
            filepaths = '    '+';\n    '.join(instance['Properties'])
            new_source = 'instance of ' + className + '\n{\n'
            new_source+= filepaths + '\n};\n'
            inventoryMofSection+=new_source

    mof_file_path = inventoryMof_path + FileName

    print(mof_file_path)

    if os.path.isfile(mof_file_path): 
        shutil.copy2(mof_file_path, mof_file_path + '.bak')
    txt = header + inventoryMofSection + footer 
    codecs.open(mof_file_path, 'w', 'utf8').write(txt)

    print(txt)

    fileNameWithoutExtension = os.path.splitext(FileName)[0] 
    conf_file_path = inventoryMof_path+ fileNameWithoutExtension + '.conf'
    conf_file_contents = '#This is auto-generated file \n \
<source> \n \
  type exec \n \
  tag ' + Tag + ' \n \
  command /opt/microsoft/omsconfig/Scripts/PerformInventory.py --InMOF ' + mof_file_path + ' --OutXML /etc/opt/omi/conf/omsconfig/configuration/' + fileNameWithoutExtension + '.xml > /dev/null && cat /etc/opt/omi/conf/omsconfig/configuration/' + fileNameWithoutExtension + '.xml \n \
  format tsv \n \
  keys xml \n \
  run_interval ' + str(RunIntervalInSeconds) + 's \n \
</source> \n \
<filter '+ Tag + '> \n \
  type ' + FilterType + ' \n \
  # Force upload even if the data has not changed \n \
  force_send_run_interval 24h \n \
  log_level warn \n \
</filter>'

    print("Conf file path" + conf_file_path)
    if os.path.isfile(conf_file_path): 
        shutil.copy2(conf_file_path, conf_file_path + '.bak')

    codecs.open(conf_file_path, 'w', 'utf8').write(conf_file_contents)
    return txt
#    os.system('sudo /opt/microsoft/omsagent/bin/service_control restart')
