

[ClassVersion("1.0.0"),FriendlyName("nxOMSAutomationWorker")]
class MSFT_nxOMSAutomationWorkerResource:OMI_BaseResource
{        
    [Key] string Name;
    [Write] boolean Enabled;
    [Write] string WorkspaceId;
};
